FROM node:20
RUN useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
USER roboshop
WORKDIR /app
COPY ./cart/*.json .
COPY ./cart/*.js .
RUN npm install
ENV REDIS_HOST="redis" \
    CATALOUGE_HOST="catalogue" \
    CATALOUGE_PORT="8080"
EXPOSE 8080
CMD ["node","server.js"]
