FROM python:3.9
WORKDIR /app
COPY ./payment/*.py .
COPY ./payment/*.txt .
COPY ./payment/*.ini . 
RUN pip3 install -r requirements.txt
RUN useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
USER roboshop
EXPOSE 8080
ENV CART_HOST="cart" \
    CART_PORT="8080" \
    USER_HOST="USER" \
    USER_PORT="8080" \
    AMQP_USER="roboshop" \
    AMQP_PASS="roboshop123"
CMD ["/usr/local/bin/uwsgi","--ini","payment.ini"]

