FROM nginx:1.29.4
RUN rm -rf /usr/share/nginx/html/*
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY ./frontend/ .
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
CMD ["nginx","-g","daemon off;"] 

