FROM maven:3.9.11
WORKDIR /app
COPY ./shipping/pom.xml .
COPY ./shipping/src/ ./src
RUN mvn clean package
RUN mv target/shipping-*.jar shipping.jar
RUN useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
USER roboshop
ENV CART_ENDPOINT="cart:8080" \
    DB_HOST="mysql"
EXPOSE 8080
CMD ["java","-jar","shipping.jar"]
