FROM node:20
RUN useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
USER roboshop
WORKDIR /app
RUN apt-get update && apt-get install wget unzip && \
    wget https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 

RUN npm install
ENV REDIS_HOST="redis" \
    CATALOUGE_HOST="catalogue" \
    CATALOUGE_PORT="8080"
EXPOSE 8080
CMD ["node","server.js"]
