FROM python:3.9
RUN useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
USER roboshop
EXPOSE 8080
WORKDIR /app
RUN apt-get update && apt-get install wget unzip &&  \
    wget https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip && \
    unzip payment-v3.zip && \
    rm -rf payment-v3.zip
RUN pip3 install -r requirements.txt
ENV CART_HOST="cart"
    CART_PORT="8080"
    USER_HOST="USER"
    USER_PORT="8080"
    AMQP_USER="roboshop"
    AMQP_PASS="roboshop123"
CMD ["/usr/local/bin/wsgi","--ini","payment.ini"]

